### ISSUE TITLE
ST2 encoding issue

### ISSUE THREAD

**Issue by spamwax** [apiad/sublime-flashback#1]
Being stuck with a 32bit Mac, I have to use ST2.
After installation, I had to add
`# coding=utf-8`
to the top of flashback.py in order to fix the error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./flashback.py", line 37
SyntaxError: Non-ASCII character '\xe2' in file ./flashback.py on line 37,
but no encoding declared;
see http://www.python.org/peps/pep-0263.html for details
```

Of course there are more issues after fixing this.

**Comment by apiad** [comment]
Thank! Actually I've never tested it on ST2, so it's awesome that all it had was an encoding error. I'll re-check it and maybe update it with proper compatibility with ST2.
